#python3 DASH_EURO_BOT.py
#python3 POL_EUR_trallingloss.py
#python3 DASH_EURO_traillingloss.py
#python3 DASH_EUR_traillingloss_multiple_orders.py
python3 DASH_EURO_traillingloss_multiple_orders_loop.py
